### ISSUE TITLE
Protocol Injection Error

### ISSUE THREAD

**Issue by MianiteWorlds** [Fupery/ArtMap#13] opened 2016-07-28 12:25 UTC
Honestly expected better from a PREMIUM plugin..
the whole server freezes and the console spams

me.Fupery.ArtMap.Protocol.ArtistProtocol.uninjectPlayer(ArtistProtocol.java:36)
28.07 14:22:04 [Server] WARN at me.Fupery.ArtMap.Protocol.ArtistProtocol.getChannel(ArtistProtocol.java:64

fix it now...

**Comment by Fupery** [comment] 2016-07-28 12:43
Hey there, I haven't seen this issue before on any server. If you could please provide me with:

1. Your server version
2. What exactly you were doing when this happened
3. The full error message

Then I can have a look and try and figure this out.

**Comment by MianiteWorlds** [comment] 2016-07-28 16:31
version 1.10.2 spigot paper
right clicking the thingy to paint on it
full error message, basiclly all i got
protocollib wont work for me idk why

**Comment by Fupery** [comment] 2016-07-29 00:00
Hey: So the issue is to do with the reflection access permissions on your system. It _should_ be fixed in the update I've just released, let me know if not - if it isn't, there will just be a single error message now.

**Comment by Fupery** [comment] 2016-07-31 04:32
Issue appears to be solved

**Closed by Fupery** 2016-07-31 04:32 UTC
Labels: bug
