### ISSUE TITLE
Blocking users from working on their own art

### ISSUE THREAD

**Issue by dart737** [Fupery/ArtMap#41] opened 2017-03-11 19:51 UTC
This has happened several times using both the newest update and the updates from about a month ago. When the server crashes, or simply randomly (This most recent time, they didn't even leave the server, just left the area) if a person leaves their art on an easel, it will randomly tell that person "You cannot edit art that isn't yours" despite them having just worked on that piece.
Here is my error log: http://pastebin.com/8E6DtMrv

**Comment by mibby** [comment] 2017-03-15 07:52
Sounds similar to this issue.
https://github.com/Fupery/ArtMap/issues/38

**Comment by Fupery** [comment] 2017-03-16 11:56
Yeah, this happens when a player isn't properly removed from the 'painting players' list on a crash or some other unexpected event. I'll look into the cause of your errors, and see if I can make it handle this issue better.

**Comment by dart737** [comment] 2017-03-16 16:50
One thought I had is you could potentially give us the option in the config to entirely allow or deny people from allowing a blocking of players from editing other people's paintings. I don't have too many people on my server where that would become an issue, so an optional quick-fix would be just to give the option to disable the system entirely, I suppose.

**Comment by Fupery** [comment] 2017-03-16 22:27
That's already how it works; this error message is normally sent if a player tries to use an easel that another player is _currently_ painting on. The issue happens when the painting handler thinks that a player is still currently using the easel, so it stops others from using it at the same time.

**Comment by Fupery** [comment] 2017-04-20 03:57
This should be fixed in version [2.6](https://www.spigotmc.org/resources/artmap-make-custom-textures-and-paintings-with-no-resource-pack-✍.26667/update?update=157774)

**Closed by Fupery** 2017-04-20 03:57 UTC
Labels: bug
